// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: examples/transfer.proto

package com.mjoys.zjh.proto;

public final class Protobufs {
  private Protobufs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string objectId = 1;</code>
     */
    java.lang.String getObjectId();
    /**
     * <code>string objectId = 1;</code>
     */
    com.google.protobuf.ByteString
        getObjectIdBytes();

    /**
     * <code>string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>bool mobilePhoneNumberVerified = 3;</code>
     */
    boolean getMobilePhoneNumberVerified();

    /**
     * <code>string mobilePhoneNumber = 4;</code>
     */
    java.lang.String getMobilePhoneNumber();
    /**
     * <code>string mobilePhoneNumber = 4;</code>
     */
    com.google.protobuf.ByteString
        getMobilePhoneNumberBytes();

    /**
     * <code>int32 totalInning = 5;</code>
     */
    int getTotalInning();

    /**
     * <code>int32 winInning = 6;</code>
     */
    int getWinInning();

    /**
     * <code>int32 diamond = 7;</code>
     */
    int getDiamond();

    /**
     * <code>int32 coin = 8;</code>
     */
    int getCoin();

    /**
     * <code>string deviceId = 9;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>string deviceId = 9;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>int32 id = 10;</code>
     */
    int getId();

    /**
     * <code>string authData = 11;</code>
     */
    java.lang.String getAuthData();
    /**
     * <code>string authData = 11;</code>
     */
    com.google.protobuf.ByteString
        getAuthDataBytes();

    /**
     * <code>uint64 createdAt = 12;</code>
     */
    long getCreatedAt();

    /**
     * <code>uint64 updatedAt = 13;</code>
     */
    long getUpdatedAt();

    /**
     * <pre>
     * for test
     * </pre>
     *
     * <code>bool specialMode = 14;</code>
     */
    boolean getSpecialMode();

    /**
     * <code>string headerUrl = 15;</code>
     */
    java.lang.String getHeaderUrl();
    /**
     * <code>string headerUrl = 15;</code>
     */
    com.google.protobuf.ByteString
        getHeaderUrlBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      objectId_ = "";
      username_ = "";
      mobilePhoneNumberVerified_ = false;
      mobilePhoneNumber_ = "";
      totalInning_ = 0;
      winInning_ = 0;
      diamond_ = 0;
      coin_ = 0;
      deviceId_ = "";
      id_ = 0;
      authData_ = "";
      createdAt_ = 0L;
      updatedAt_ = 0L;
      specialMode_ = false;
      headerUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              objectId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 24: {

              mobilePhoneNumberVerified_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mobilePhoneNumber_ = s;
              break;
            }
            case 40: {

              totalInning_ = input.readInt32();
              break;
            }
            case 48: {

              winInning_ = input.readInt32();
              break;
            }
            case 56: {

              diamond_ = input.readInt32();
              break;
            }
            case 64: {

              coin_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 80: {

              id_ = input.readInt32();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              authData_ = s;
              break;
            }
            case 96: {

              createdAt_ = input.readUInt64();
              break;
            }
            case 104: {

              updatedAt_ = input.readUInt64();
              break;
            }
            case 112: {

              specialMode_ = input.readBool();
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              headerUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mjoys.zjh.proto.Protobufs.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mjoys.zjh.proto.Protobufs.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mjoys.zjh.proto.Protobufs.User.class, com.mjoys.zjh.proto.Protobufs.User.Builder.class);
    }

    public static final int OBJECTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object objectId_;
    /**
     * <code>string objectId = 1;</code>
     */
    public java.lang.String getObjectId() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectId_ = s;
        return s;
      }
    }
    /**
     * <code>string objectId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getObjectIdBytes() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILEPHONENUMBERVERIFIED_FIELD_NUMBER = 3;
    private boolean mobilePhoneNumberVerified_;
    /**
     * <code>bool mobilePhoneNumberVerified = 3;</code>
     */
    public boolean getMobilePhoneNumberVerified() {
      return mobilePhoneNumberVerified_;
    }

    public static final int MOBILEPHONENUMBER_FIELD_NUMBER = 4;
    private volatile java.lang.Object mobilePhoneNumber_;
    /**
     * <code>string mobilePhoneNumber = 4;</code>
     */
    public java.lang.String getMobilePhoneNumber() {
      java.lang.Object ref = mobilePhoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobilePhoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string mobilePhoneNumber = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMobilePhoneNumberBytes() {
      java.lang.Object ref = mobilePhoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobilePhoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALINNING_FIELD_NUMBER = 5;
    private int totalInning_;
    /**
     * <code>int32 totalInning = 5;</code>
     */
    public int getTotalInning() {
      return totalInning_;
    }

    public static final int WININNING_FIELD_NUMBER = 6;
    private int winInning_;
    /**
     * <code>int32 winInning = 6;</code>
     */
    public int getWinInning() {
      return winInning_;
    }

    public static final int DIAMOND_FIELD_NUMBER = 7;
    private int diamond_;
    /**
     * <code>int32 diamond = 7;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    public static final int COIN_FIELD_NUMBER = 8;
    private int coin_;
    /**
     * <code>int32 coin = 8;</code>
     */
    public int getCoin() {
      return coin_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 9;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string deviceId = 9;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 10;
    private int id_;
    /**
     * <code>int32 id = 10;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int AUTHDATA_FIELD_NUMBER = 11;
    private volatile java.lang.Object authData_;
    /**
     * <code>string authData = 11;</code>
     */
    public java.lang.String getAuthData() {
      java.lang.Object ref = authData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authData_ = s;
        return s;
      }
    }
    /**
     * <code>string authData = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAuthDataBytes() {
      java.lang.Object ref = authData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDAT_FIELD_NUMBER = 12;
    private long createdAt_;
    /**
     * <code>uint64 createdAt = 12;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 13;
    private long updatedAt_;
    /**
     * <code>uint64 updatedAt = 13;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }

    public static final int SPECIALMODE_FIELD_NUMBER = 14;
    private boolean specialMode_;
    /**
     * <pre>
     * for test
     * </pre>
     *
     * <code>bool specialMode = 14;</code>
     */
    public boolean getSpecialMode() {
      return specialMode_;
    }

    public static final int HEADERURL_FIELD_NUMBER = 15;
    private volatile java.lang.Object headerUrl_;
    /**
     * <code>string headerUrl = 15;</code>
     */
    public java.lang.String getHeaderUrl() {
      java.lang.Object ref = headerUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string headerUrl = 15;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderUrlBytes() {
      java.lang.Object ref = headerUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getObjectIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectId_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (mobilePhoneNumberVerified_ != false) {
        output.writeBool(3, mobilePhoneNumberVerified_);
      }
      if (!getMobilePhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mobilePhoneNumber_);
      }
      if (totalInning_ != 0) {
        output.writeInt32(5, totalInning_);
      }
      if (winInning_ != 0) {
        output.writeInt32(6, winInning_);
      }
      if (diamond_ != 0) {
        output.writeInt32(7, diamond_);
      }
      if (coin_ != 0) {
        output.writeInt32(8, coin_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deviceId_);
      }
      if (id_ != 0) {
        output.writeInt32(10, id_);
      }
      if (!getAuthDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, authData_);
      }
      if (createdAt_ != 0L) {
        output.writeUInt64(12, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeUInt64(13, updatedAt_);
      }
      if (specialMode_ != false) {
        output.writeBool(14, specialMode_);
      }
      if (!getHeaderUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, headerUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getObjectIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectId_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (mobilePhoneNumberVerified_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, mobilePhoneNumberVerified_);
      }
      if (!getMobilePhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mobilePhoneNumber_);
      }
      if (totalInning_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, totalInning_);
      }
      if (winInning_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, winInning_);
      }
      if (diamond_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, diamond_);
      }
      if (coin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, coin_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deviceId_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, id_);
      }
      if (!getAuthDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, authData_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(13, updatedAt_);
      }
      if (specialMode_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, specialMode_);
      }
      if (!getHeaderUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, headerUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mjoys.zjh.proto.Protobufs.User)) {
        return super.equals(obj);
      }
      com.mjoys.zjh.proto.Protobufs.User other = (com.mjoys.zjh.proto.Protobufs.User) obj;

      boolean result = true;
      result = result && getObjectId()
          .equals(other.getObjectId());
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && (getMobilePhoneNumberVerified()
          == other.getMobilePhoneNumberVerified());
      result = result && getMobilePhoneNumber()
          .equals(other.getMobilePhoneNumber());
      result = result && (getTotalInning()
          == other.getTotalInning());
      result = result && (getWinInning()
          == other.getWinInning());
      result = result && (getDiamond()
          == other.getDiamond());
      result = result && (getCoin()
          == other.getCoin());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && (getId()
          == other.getId());
      result = result && getAuthData()
          .equals(other.getAuthData());
      result = result && (getCreatedAt()
          == other.getCreatedAt());
      result = result && (getUpdatedAt()
          == other.getUpdatedAt());
      result = result && (getSpecialMode()
          == other.getSpecialMode());
      result = result && getHeaderUrl()
          .equals(other.getHeaderUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OBJECTID_FIELD_NUMBER;
      hash = (53 * hash) + getObjectId().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + MOBILEPHONENUMBERVERIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMobilePhoneNumberVerified());
      hash = (37 * hash) + MOBILEPHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMobilePhoneNumber().hashCode();
      hash = (37 * hash) + TOTALINNING_FIELD_NUMBER;
      hash = (53 * hash) + getTotalInning();
      hash = (37 * hash) + WININNING_FIELD_NUMBER;
      hash = (53 * hash) + getWinInning();
      hash = (37 * hash) + DIAMOND_FIELD_NUMBER;
      hash = (53 * hash) + getDiamond();
      hash = (37 * hash) + COIN_FIELD_NUMBER;
      hash = (53 * hash) + getCoin();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + AUTHDATA_FIELD_NUMBER;
      hash = (53 * hash) + getAuthData().hashCode();
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedAt());
      hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdatedAt());
      hash = (37 * hash) + SPECIALMODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSpecialMode());
      hash = (37 * hash) + HEADERURL_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mjoys.zjh.proto.Protobufs.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mjoys.zjh.proto.Protobufs.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.mjoys.zjh.proto.Protobufs.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mjoys.zjh.proto.Protobufs.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mjoys.zjh.proto.Protobufs.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mjoys.zjh.proto.Protobufs.User.class, com.mjoys.zjh.proto.Protobufs.User.Builder.class);
      }

      // Construct using com.mjoys.zjh.proto.Protobufs.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        objectId_ = "";

        username_ = "";

        mobilePhoneNumberVerified_ = false;

        mobilePhoneNumber_ = "";

        totalInning_ = 0;

        winInning_ = 0;

        diamond_ = 0;

        coin_ = 0;

        deviceId_ = "";

        id_ = 0;

        authData_ = "";

        createdAt_ = 0L;

        updatedAt_ = 0L;

        specialMode_ = false;

        headerUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mjoys.zjh.proto.Protobufs.internal_static_User_descriptor;
      }

      public com.mjoys.zjh.proto.Protobufs.User getDefaultInstanceForType() {
        return com.mjoys.zjh.proto.Protobufs.User.getDefaultInstance();
      }

      public com.mjoys.zjh.proto.Protobufs.User build() {
        com.mjoys.zjh.proto.Protobufs.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mjoys.zjh.proto.Protobufs.User buildPartial() {
        com.mjoys.zjh.proto.Protobufs.User result = new com.mjoys.zjh.proto.Protobufs.User(this);
        result.objectId_ = objectId_;
        result.username_ = username_;
        result.mobilePhoneNumberVerified_ = mobilePhoneNumberVerified_;
        result.mobilePhoneNumber_ = mobilePhoneNumber_;
        result.totalInning_ = totalInning_;
        result.winInning_ = winInning_;
        result.diamond_ = diamond_;
        result.coin_ = coin_;
        result.deviceId_ = deviceId_;
        result.id_ = id_;
        result.authData_ = authData_;
        result.createdAt_ = createdAt_;
        result.updatedAt_ = updatedAt_;
        result.specialMode_ = specialMode_;
        result.headerUrl_ = headerUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mjoys.zjh.proto.Protobufs.User) {
          return mergeFrom((com.mjoys.zjh.proto.Protobufs.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mjoys.zjh.proto.Protobufs.User other) {
        if (other == com.mjoys.zjh.proto.Protobufs.User.getDefaultInstance()) return this;
        if (!other.getObjectId().isEmpty()) {
          objectId_ = other.objectId_;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (other.getMobilePhoneNumberVerified() != false) {
          setMobilePhoneNumberVerified(other.getMobilePhoneNumberVerified());
        }
        if (!other.getMobilePhoneNumber().isEmpty()) {
          mobilePhoneNumber_ = other.mobilePhoneNumber_;
          onChanged();
        }
        if (other.getTotalInning() != 0) {
          setTotalInning(other.getTotalInning());
        }
        if (other.getWinInning() != 0) {
          setWinInning(other.getWinInning());
        }
        if (other.getDiamond() != 0) {
          setDiamond(other.getDiamond());
        }
        if (other.getCoin() != 0) {
          setCoin(other.getCoin());
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getAuthData().isEmpty()) {
          authData_ = other.authData_;
          onChanged();
        }
        if (other.getCreatedAt() != 0L) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.getUpdatedAt() != 0L) {
          setUpdatedAt(other.getUpdatedAt());
        }
        if (other.getSpecialMode() != false) {
          setSpecialMode(other.getSpecialMode());
        }
        if (!other.getHeaderUrl().isEmpty()) {
          headerUrl_ = other.headerUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mjoys.zjh.proto.Protobufs.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mjoys.zjh.proto.Protobufs.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object objectId_ = "";
      /**
       * <code>string objectId = 1;</code>
       */
      public java.lang.String getObjectId() {
        java.lang.Object ref = objectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string objectId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getObjectIdBytes() {
        java.lang.Object ref = objectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string objectId = 1;</code>
       */
      public Builder setObjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        objectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string objectId = 1;</code>
       */
      public Builder clearObjectId() {
        
        objectId_ = getDefaultInstance().getObjectId();
        onChanged();
        return this;
      }
      /**
       * <code>string objectId = 1;</code>
       */
      public Builder setObjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        objectId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private boolean mobilePhoneNumberVerified_ ;
      /**
       * <code>bool mobilePhoneNumberVerified = 3;</code>
       */
      public boolean getMobilePhoneNumberVerified() {
        return mobilePhoneNumberVerified_;
      }
      /**
       * <code>bool mobilePhoneNumberVerified = 3;</code>
       */
      public Builder setMobilePhoneNumberVerified(boolean value) {
        
        mobilePhoneNumberVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool mobilePhoneNumberVerified = 3;</code>
       */
      public Builder clearMobilePhoneNumberVerified() {
        
        mobilePhoneNumberVerified_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object mobilePhoneNumber_ = "";
      /**
       * <code>string mobilePhoneNumber = 4;</code>
       */
      public java.lang.String getMobilePhoneNumber() {
        java.lang.Object ref = mobilePhoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobilePhoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobilePhoneNumber = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMobilePhoneNumberBytes() {
        java.lang.Object ref = mobilePhoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobilePhoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobilePhoneNumber = 4;</code>
       */
      public Builder setMobilePhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobilePhoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobilePhoneNumber = 4;</code>
       */
      public Builder clearMobilePhoneNumber() {
        
        mobilePhoneNumber_ = getDefaultInstance().getMobilePhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string mobilePhoneNumber = 4;</code>
       */
      public Builder setMobilePhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobilePhoneNumber_ = value;
        onChanged();
        return this;
      }

      private int totalInning_ ;
      /**
       * <code>int32 totalInning = 5;</code>
       */
      public int getTotalInning() {
        return totalInning_;
      }
      /**
       * <code>int32 totalInning = 5;</code>
       */
      public Builder setTotalInning(int value) {
        
        totalInning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalInning = 5;</code>
       */
      public Builder clearTotalInning() {
        
        totalInning_ = 0;
        onChanged();
        return this;
      }

      private int winInning_ ;
      /**
       * <code>int32 winInning = 6;</code>
       */
      public int getWinInning() {
        return winInning_;
      }
      /**
       * <code>int32 winInning = 6;</code>
       */
      public Builder setWinInning(int value) {
        
        winInning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 winInning = 6;</code>
       */
      public Builder clearWinInning() {
        
        winInning_ = 0;
        onChanged();
        return this;
      }

      private int diamond_ ;
      /**
       * <code>int32 diamond = 7;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>int32 diamond = 7;</code>
       */
      public Builder setDiamond(int value) {
        
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 diamond = 7;</code>
       */
      public Builder clearDiamond() {
        
        diamond_ = 0;
        onChanged();
        return this;
      }

      private int coin_ ;
      /**
       * <code>int32 coin = 8;</code>
       */
      public int getCoin() {
        return coin_;
      }
      /**
       * <code>int32 coin = 8;</code>
       */
      public Builder setCoin(int value) {
        
        coin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 coin = 8;</code>
       */
      public Builder clearCoin() {
        
        coin_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string deviceId = 9;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceId = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 9;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 9;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 9;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 10;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 10;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 10;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object authData_ = "";
      /**
       * <code>string authData = 11;</code>
       */
      public java.lang.String getAuthData() {
        java.lang.Object ref = authData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authData = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAuthDataBytes() {
        java.lang.Object ref = authData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authData = 11;</code>
       */
      public Builder setAuthData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authData = 11;</code>
       */
      public Builder clearAuthData() {
        
        authData_ = getDefaultInstance().getAuthData();
        onChanged();
        return this;
      }
      /**
       * <code>string authData = 11;</code>
       */
      public Builder setAuthDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authData_ = value;
        onChanged();
        return this;
      }

      private long createdAt_ ;
      /**
       * <code>uint64 createdAt = 12;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <code>uint64 createdAt = 12;</code>
       */
      public Builder setCreatedAt(long value) {
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 createdAt = 12;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      private long updatedAt_ ;
      /**
       * <code>uint64 updatedAt = 13;</code>
       */
      public long getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <code>uint64 updatedAt = 13;</code>
       */
      public Builder setUpdatedAt(long value) {
        
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 updatedAt = 13;</code>
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = 0L;
        onChanged();
        return this;
      }

      private boolean specialMode_ ;
      /**
       * <pre>
       * for test
       * </pre>
       *
       * <code>bool specialMode = 14;</code>
       */
      public boolean getSpecialMode() {
        return specialMode_;
      }
      /**
       * <pre>
       * for test
       * </pre>
       *
       * <code>bool specialMode = 14;</code>
       */
      public Builder setSpecialMode(boolean value) {
        
        specialMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * for test
       * </pre>
       *
       * <code>bool specialMode = 14;</code>
       */
      public Builder clearSpecialMode() {
        
        specialMode_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object headerUrl_ = "";
      /**
       * <code>string headerUrl = 15;</code>
       */
      public java.lang.String getHeaderUrl() {
        java.lang.Object ref = headerUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headerUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string headerUrl = 15;</code>
       */
      public com.google.protobuf.ByteString
          getHeaderUrlBytes() {
        java.lang.Object ref = headerUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headerUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string headerUrl = 15;</code>
       */
      public Builder setHeaderUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headerUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string headerUrl = 15;</code>
       */
      public Builder clearHeaderUrl() {
        
        headerUrl_ = getDefaultInstance().getHeaderUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string headerUrl = 15;</code>
       */
      public Builder setHeaderUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headerUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.mjoys.zjh.proto.Protobufs.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mjoys.zjh.proto.Protobufs.User();
    }

    public static com.mjoys.zjh.proto.Protobufs.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.mjoys.zjh.proto.Protobufs.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027examples/transfer.proto\"\255\002\n\004User\022\020\n\010ob" +
      "jectId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022!\n\031mobile" +
      "PhoneNumberVerified\030\003 \001(\010\022\031\n\021mobilePhone" +
      "Number\030\004 \001(\t\022\023\n\013totalInning\030\005 \001(\005\022\021\n\twin" +
      "Inning\030\006 \001(\005\022\017\n\007diamond\030\007 \001(\005\022\014\n\004coin\030\010 " +
      "\001(\005\022\020\n\010deviceId\030\t \001(\t\022\n\n\002id\030\n \001(\005\022\020\n\010aut" +
      "hData\030\013 \001(\t\022\021\n\tcreatedAt\030\014 \001(\004\022\021\n\tupdate" +
      "dAt\030\r \001(\004\022\023\n\013specialMode\030\016 \001(\010\022\021\n\theader" +
      "Url\030\017 \001(\tB \n\023com.mjoys.zjh.protoB\tProtob" +
      "ufsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "ObjectId", "Username", "MobilePhoneNumberVerified", "MobilePhoneNumber", "TotalInning", "WinInning", "Diamond", "Coin", "DeviceId", "Id", "AuthData", "CreatedAt", "UpdatedAt", "SpecialMode", "HeaderUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
